package com.hackathon.backend.locationsservice.Services.BarrierlessCriteriaScope;

import com.hackathon.backend.locationsservice.Controllers.RequestDTO.Mappers.Read.BarrierlessCriteriaScope.BarrierlessCriteriaGroupReadMapper;
import com.hackathon.backend.locationsservice.Controllers.RequestDTO.Read.BarrierlessCriteriaScope.BarrierlessCriteriaGroupReadDTO;
import com.hackathon.backend.locationsservice.Domain.Core.BarrierlessCriteriaScope.BarrierlessCriteriaGroup;
import com.hackathon.backend.locationsservice.Repositories.BarrierlessCriteriaScope.BarrierlessCriteriaGroupRepository;
import com.hackathon.backend.locationsservice.Services.GeneralService;
import org.springframework.stereotype.Service;

@Service
public class BarrierlessCriteriaGroupService extends GeneralService<BarrierlessCriteriaGroupReadMapper, BarrierlessCriteriaGroupReadDTO, BarrierlessCriteriaGroup,BarrierlessCriteriaGroupRepository> {

    BarrierlessCriteriaGroupService(BarrierlessCriteriaGroupRepository barrierlessCriteriaGroupRepository, BarrierlessCriteriaGroupReadMapper barrierlessCriteriaGroupReadMapper){
        super(barrierlessCriteriaGroupRepository,BarrierlessCriteriaGroup.class,barrierlessCriteriaGroupReadMapper);
    }


}
